version: '3.8'
services:
  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ergon
  ergon:
    build: .
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/ergon"
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    ports:
      - '8080:8080'
    depends_on:
      - db


volumes:
  pgdata: