services:
  - type: web
    plan: free
    name: Ergon
    runtime: image
    image:
      url: "docker.io/tibss/ergon:latest"
      creds:
        fromRegistryCreds:
          name: docker-creds
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?user=${DATABASE_USERNAME}&password=${DATABASE_PASSWORD}&sslmode=require"
      - key: DATABASE_HOST
        fromDatabase:
          name: ergon-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: ergon-db
          property: port
      - key: DATABASE_NAME
        fromDatabase:
          name: ergon-db
          property: database
      - key: DATABASE_USERNAME
        fromDatabase:
          name: ergon-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: ergon-db
          property: password
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: ergon-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: ergon-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: ergon-db
    databaseName: ergon
    user: ergon_user
    plan: free
    postgresMajorVersion: "13"