services:
  - type: web
    runtime: docker
    image:
      url: "tibss/ergon:latest"
    plan: free
    name: Ergon
    repo: https://github.com/tib-source/Ergon.git
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: ergon-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: ergon-db
    databaseName: ergon
    user: ergon_user
    plan: free
    postgresMajorVersion: "13"