# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Main
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  JAVA_DISTRO: 'microsoft'
  JAVA_MAJOR_VERSION: '17.0.8'
  NODE_MAJOR_VERSION: '20.14.0'


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Setup :: Checkout'
        uses: 'actions/checkout@v4'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: 'Setup :: Determine Java and Node versions'
        run: |
          echo "JAVA_DISTRO=$(cat .tool-versions | grep java | awk '{ print $2 }' | awk -F- '{ print $1 }')" >> $GITHUB_ENV
          echo "JAVA_MAJOR_VERSION=$(cat .tool-versions | grep java | awk '{ print $2 }' | awk -F- '{ print $2 }' | awk -F. '{ print $1 }')" >> $GITHUB_ENV
          echo "NODE_MAJOR_VERSION=$(cat .tool-versions | grep nodejs | awk '{ print $2 }' | awk -F. '{ print $1 }')" >> $GITHUB_ENV

      - name: 'Setup :: Java'
        uses: 'actions/setup-java@v3'
        with:
          distribution: 'microsoft'
          java-version: '17.0.8'
          cache: 'maven'


      - name: 'Setup :: Node'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '20.14.0'
          cache: 'npm'
          cache-dependency-path: 'src/main/client/package-lock.json'

      - name: 'Application :: Build'
        run: ./mvnw spring-boot:run -Dspring-boot.run.profiles=prod

      - name: List JAR files (for verification)
        run: ls -la target/*.jar

      - name: Login to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: 'docker/login-action@v3'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: tibss/ergon:latest
